### ISSUE TITLE
Wrong command to disbable storage ?

### ISSUE THREAD

**Issue by Tryum** [microsoft/nubesgen-actions#17]
Hey,

Just reading through the code to check how nubesgen works.
I think there's an issue with the gitops-apply-terraform action :
the last step, **Disable local IP access to the Storage Account** has the same command line as **Authorize local IP to access the Storage Account** : `az storage account update --name $TF_STORAGE_ACCOUNT --default-action Allow`

Shouldn't it be : `az storage account update --name $TF_STORAGE_ACCOUNT --default-action Deny` ?

https://github.com/microsoft/nubesgen-actions/blob/19b096293c0576c9925680a1b3f9fd4171e373eb/gitops-apply-terraform/action.yml#L104

**Comment by jdubois** [comment]
Thank you! Yes you are correct and I just did the fix (that's what closed this issue automatically).
